# Goal
int32                        arm
geometry_msgs/PoseStamped    required_pose
geometry_msgs/TwistStamped   constraint
---
# Result
geometry_msgs/PoseStamped    end_pose
---
# Feedback
geometry_msgs/PoseStamped    current_pose
geometry_msgs/TwistStamped   current_constraint
