# Goal
string                         arm
geometry_msgs/TwistStamped     required_velocity
geometry_msgs/TwistStamped     constraint
---
# Result
geometry_msgs/TwistStamped     end_velocity
---
# Feedback
geometry_msgs/TwistStamped     current_velocity
geometry_msgs/TwistStamped     current_constraint