controller_list:
  - name: "/jaco_arm"
    # action_ns: smooth_arm_controller/trajectory 
    action_ns: joint_velocity_controller/trajectory
    type: FollowJointTrajectory
    joints: 
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6