open_close_gripper_on_init: true
plugins: 
    - 
        name: mico
        type: "arm_controller_plugins::ArmControllerMico"
    # - 
    #   name: robai_left
    #   type: "arm_controller_plugins::ArmControllerRobai"
    # - 
    # name: robai_right
    # type: "arm_controller_plugins::ArmControllerRobai"